### ISSUE TITLE
Debian 12: can't run plexsync

### ISSUE THREAD

**Issue by cabrinha** [arsaboo/beets-plexsync#53]
```
** error loading plugin plexsync:
Traceback (most recent call last):
  File "/home/yuppie/.local/share/pipx/venvs/beets/lib/python3.12/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuppie/.local/share/pipx/venvs/beets/lib/python3.12/site-packages/beetsplug/plexsync.py", line 20, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'
```

**Comment by arsaboo** [comment]
Try manually installing dateutil
